In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/home/gh05tm4n/Documents/Projects/True People Search - Scrapper/output_files/Cleaned Output/Cleaned_Scraped_Details.csv')

In [3]:
df.shape

(2307, 9)

In [4]:
df.head()

,Unnamed: 0,Name,Age,Address,Phone1,Phone2,Phone3,Phone4,Phone5
0,0,Philip Donald,62,126 Pinecrest Ln Cheney WA 99004-8727,(313) 204-5005,(313) 538-1208,(313) 433-8657,NaN,NaN
1,1,Seaton Donald,62,2300 A St Bellingham WA 98225-3606,(206) 232-2221,(949) 232-2221,(949) 439-7833,NaN,NaN
2,2,John R Donald,66,43-45 Laurel St Watertown MA 02472,(360) 400-2315,(360) 400-0000,(360) 458-7986,(360) 960-8424,(617) 924-6897
3,3,Ma Martin Donald,78,1700 Laguna St #F Concord CA 94520-2999,(925) 826-3101,(303) 375-1947,(925) 639-4048,NaN,NaN
4,4,Kauffman Donald,81,9830 Ashton Pines Ct Las Vegas NV 89147-7257,(702) 449-4278,(702) 232-9112,(541) 218-6802,NaN,NaN

In [5]:
help(df.duplicated)

Help on method duplicated in module pandas.core.frame:

duplicated(subset=None, keep='first') method of pandas.core.frame.DataFrame instance
    Return boolean Series denoting duplicate rows, optionally only
    considering certain columns.

    Parameters
    ----------
    subset : column label or sequence of labels, optional
        Only consider certain columns for identifying duplicates, by
        default use all of the columns
    keep : {'first', 'last', False}, default 'first'
        - ``first`` : Mark duplicates as ``True`` except for the
          first occurrence.
        - ``last`` : Mark duplicates as ``True`` except for the
          last occurrence.
        - False : Mark all duplicates as ``True``.

    Returns
    -------
    duplicated : Series

In [22]:
duplicate = df[( df.duplicated(["Name","Address"]) )]

In [10]:
df.iloc[90]

Unnamed: 0                                            99
Name                                     Dennis J Mickey
Age                                                   73
Address       1416 Whitehouse Ave Buckley  WA 98321-8956
Phone1                                    (360) 829-4206
Phone2                                    (360) 829-5267
Phone3                                    (360) 829-6530
Phone4                                    (360) 533-1112
Phone5                                    (909) 591-8690
Name: 90, dtype: object

In [11]:
df.iloc[99]

Unnamed: 0                                          108
Name                                         A H Mickey
Age                                                  89
Address       24215 Taree Dr NE Kingston  WA 98346-9204
Phone1                                   (360) 881-0744
Phone2                                   (360) 297-8235
Phone3                                   (334) 297-8235
Phone4                                              NaN
Phone5                                              NaN
Name: 99, dtype: object

In [25]:
duplicate.head(137)

,Unnamed: 0,Name,Age,Address,Phone1,Phone2,Phone3,Phone4,Phone5
158,186,Bobby Everitt Mickey,81,9551 Brookline Ave Desert Hot Springs CA 9224...,(760) 329-2629,(760) 329-6171,(541) 726-5035,NaN,NaN
169,197,Carolyn M Mickey,60,569 Olli Trl Maggie Valley NC 28751-7208,(864) 756-3187,(828) 926-4156,(864) 283-0965,(706) 496-8484,(714) 668-0281
173,201,Carolyn K Mickey,60,569 Olli Trl Maggie Valley NC 28751-7208,(828) 926-4156,(864) 283-0965,(714) 668-0281,NaN,NaN
178,206,Barbara Jo Mickey,77,9551 Brookline Ave Desert Hot Springs CA 9224...,(760) 329-6171,(541) 747-3485,(760) 329-2629,NaN,NaN
179,207,A H Mickey,89,24215 Taree Dr NE Kingston WA 98346-9204,(360) 881-0744,(360) 297-8235,(334) 297-8235,NaN,NaN
182,210,Cessna Mickey,68,6507 W Mirabella St Wichita KS 67205-1002,(316) 641-3888,(316) 641-7774,(316) 721-1410,(316) 409-6374,NaN
198,227,Adele L Mickey,81,3153 Malvasia Ct Pleasanton CA 94566-6949,(925) 462-3591,(510) 388-5349,(925) 462-4293,(415) 462-4293,(510) 462-4293
227,270,C L Mickey,76,1508 El Ralfo Dr Bakersfield CA 93304-3927,(661) 831-6215,NaN,NaN,NaN,NaN
228,275,C L Mickey,76,1508 El Ralfo Dr Bakersfield CA 93304-3927,(661) 831-6215,NaN,NaN,NaN,NaN
229,278,C L Mickey,76,1508 El Ralfo Dr Bakersfield CA 93304-3927,(661) 831-6215,NaN,NaN,NaN,NaN
235,287,Mickey,79,3967 Delos Dr Las Vegas NV 89103-2534,(702) 252-0497,(702) 376-7125,(702) 254-6591,NaN,NaN
237,289,E Dpm Mickey Jr,70,9258 Troon Lakes Dr Naples FL 34109-4314,(239) 598-5363,(239) 250-1133,(239) 250-1333,(239) 566-8800,NaN
246,298,Clayton Mickey,69,7460 Mellotts Rd Fenton IL 61251-9793,(309) 887-9271,(815) 772-7211,(417) 628-3383,(208) 289-5033,(509) 758-7963
252,304,Carla S Mickey,73,PO Box 153 Boise ID 83701-0153,(208) 938-2804,NaN,NaN,NaN,NaN
256,308,Fran Mickey,90,401 S 5th St E #33 Chewelah WA 99109-9300,(509) 935-4861,(509) 884-0851,NaN,NaN,NaN
265,318,A G Mickey,85,11322 S Avenue 12 E #239 Yuma AZ 85367-6652,(928) 342-1093,(208) 264-5295,(208) 683-3527,NaN,NaN
271,328,Mickey,79,3967 Delos Dr Las Vegas NV 89103-2534,(702) 252-0497,(702) 376-7125,(702) 254-6591,NaN,NaN
272,329,Janet S Mickey,61,20 Robert Ln Ringgold GA 30736-7200,(423) 637-2890,(423) 595-9247,(706) 595-9247,NaN,NaN
284,341,Marshall Mickey,80,310 St Cloud Rd Los Angeles CA 90077-3423,(310) 553-0177,(310) 476-3347,(310) 476-0000,(310) 476-0947,(310) 201-7700
287,344,Calvin W Mickey,60,1712 Ferguson Valley Rd Mc Veytown PA 17051-9519,(814) 329-5520,(814) 542-3434,(814) 542-8068,NaN,NaN
294,351,Antoinette M Mickey,81,1841 Spring Mountain Rd Saint Helena CA 94574...,(707) 968-5375,(941) 330-4344,(941) 928-1626,(216) 320-9328,NaN
301,358,M C Mickey,61,1556 Andrew Ave Anderson CA 96007-2964,(775) 293-2449,(216) 990-8212,(530) 510-5518,NaN,NaN
306,363,Brian V Mickey,66,3301 Meadowlands Dr Sparks NV 89431-1448,(775) 331-7409,(702) 324-7663,(775) 826-3044,(206) 542-5670,(775) 324-7663
309,367,Holly Mickey,72,1880 E 10th St Silver Springs NV 89429-8659,(574) 527-5017,(219) 544-1056,(574) 267-6608,NaN,NaN
315,375,Mickey,74,1518 Delany St Pomona CA 91767-4229,(909) 964-7585,(909) 629-8592,NaN,NaN,NaN
324,384,Debra N Mickey,65,14049 State Highway 33 Gustine CA 95322-9793,(503) 227-3357,(916) 604-2534,(916) 676-3734,(207) 827-6203,(702) 229-4191
327,390,Donald Lee Mickey,94,17033 Woodcrest Dr NE Bothell WA 98011-5426,(425) 968-8910,(425) 896-0312,(702) 363-2380,NaN,NaN
329,392,Ellis W Mickey,84,422 4th St Summerville OR 97876-8169,(541) 534-5418,NaN,NaN,NaN,NaN
332,401,Brian V Mickey,66,3301 Meadowlands Dr Sparks NV 89431-1448,(775) 331-7409,(775) 826-3044,NaN,NaN,NaN
333,403,Arden Mickey,84,3215 E Cheyenne Ave North Las Vegas NV 89030-...,(702) 262-3990,(702) 682-7755,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1465,1688,Bill,71,213 Ruby St SE Tumwater WA 98501-4544,(360) 534-0441,NaN,NaN,NaN,NaN
1473,1697,Bill,74,5432 99th Ave SE Snohomish WA 98290-5707,(314) 226-0745,(214) 435-6498,(360) 853-7672,NaN,NaN
1686,1920,A Ruth Jeff,61,10171 Frontier Pl NW Silverdale WA 98383-9408,(360) 613-5304,(360) 697-5884,(360) 697-7120,NaN,NaN
1715,1949,Cameron Jeff,62,1350 Stella Rd Longview WA 98632-9727,(360) 414-7017,(360) 423-5401,(925) 930-7671,NaN,NaN
1724,1959,Andersen Jeff,63,1163 Wendell St Twin Falls ID 83301-4275,(208) 420-5530,(208) 736-7426,(208) 669-4064,NaN,NaN
1731,1966,Harris Jeff,62,825 Country Clb Tooele UT 84074-9627,(435) 841-7332,(435) 882-4540,(801) 882-4540,(435) 882-2492,(909) 875-4067
1753,1988,Bob Jeff,71,4403 Blackstone Way Bellingham WA 98226-7780,(360) 383-0213,(360) 366-2291,(360) 384-4957,(206) 384-4957,NaN
1771,2006,Bragg C Jeff,60,2400 Calkins Ave Idaho Falls ID 83402-4535,(208) 227-6435,(208) 521-1851,(208) 523-3843,(208) 709-0841,(208) 948-4542
1784,2019,Anthony Jeff,61,3028 Eggleston Rd Crowley TX 76036-5604,(817) 297-7121,(817) 426-2061,(310) 422-8911,(702) 468-0547,(775) 468-0547
1794,2029,Athey Jeff,62,2033 1st Ave #8 Seattle WA 98121-2132,(206) 448-7832,(816) 531-0590,(208) 762-3779,(816) 359-6499,NaN
1981,2228,Bruce J Rick,64,1016 W St NW Auburn WA 98001-3832,(253) 850-1571,NaN,NaN,NaN,NaN
2012,2268,A Rick,63,630 NE Newkirk Rd Belfair WA 98528-9689,(253) 344-1489,(253) 445-0387,(253) 874-0184,(253) 770-1094,(907) 966-2777
2015,2271,Rick,96,9218 Williams Rd Chardon OH 44024-9296,(440) 286-7213,(281) 914-7731,(440) 413-0456,NaN,NaN
2050,2309,Rick,70,1123 Treemont Way SE Fall City WA 98024-7426,(949) 612-8396,(949) 474-0756,(714) 330-5950,NaN,NaN
2063,2322,Rick,63,3157 Maple St San Diego CA 92104-5026,(619) 890-7425,(619) 969-1634,(619) 754-3582,NaN,NaN
2083,2342,F Rick,61,2720 Barreville Rd McHenry IL 60050-8113,(406) 461-1446,(406) 458-8923,(386) 437-2100,NaN,NaN
2084,2343,A H Rick,69,15834 Kamb Rd Mount Vernon WA 98273-8142,(360) 424-5934,(360) 387-6613,(360) 422-6406,NaN,NaN
2121,2381,Rick,73,8842 Midvale Ave N #A Seattle WA 98103-4034,(949) 654-9614,(714) 654-9614,(949) 362-5278,(562) 595-1261,(949) 595-1261
2124,2384,Jesus Luis Mateo,65,933 W Nebraska Ave Caruthers CA 93609-9705,(559) 864-4340,(559) 916-3395,(559) 976-3395,(559) 864-8182,(559) 864-8204
2126,2386,Rick,65,325 Washington Ave S #10 Kent WA 98032-5767,(714) 446-8890,(714) 990-5596,NaN,NaN,NaN
2133,2393,A Rick,67,5564 SW Erickson Ave Beaverton OR 97005-3882,(503) 919-4070,(347) 223-9579,(503) 329-3139,NaN,NaN
2157,2423,A Rick,61,1018 E 3rd St #D Long Beach CA 90802-3453,NaN,NaN,NaN,NaN,NaN
2160,2426,A Rick,61,1018 E 3rd St #D Long Beach CA 90802-3453,NaN,NaN,NaN,NaN,NaN
2166,2436,Albert H Rick,64,1227 S 4th Ave #13 Pocatello ID 83201-6716,(208) 232-0003,(202) 232-0003,(208) 573-4698,NaN,NaN
2169,2439,Bruce Arden Rick,76,203 Hitchcock Way #201 Santa Barbara CA 93105...,(805) 845-0922,(805) 620-0740,(520) 408-1700,NaN,NaN
2188,2460,A Rick,60,13117 287th Ave SE Monroe WA 98272-7508,(615) 943-7770,(518) 541-3641,(707) 438-0292,(405) 359-1883,(410) 643-5798
2229,2502,Andrew Rick,77,1220 6th Ave SW Olympia WA 98502-5420,(360) 753-4941,(360) 533-0242,(360) 943-6403,NaN,NaN
2230,2503,A Jr Rick Jr,64,10254 W Shelborne Dr Boise ID 83709-1230,(208) 514-0136,(208) 272-1289,(805) 485-0000,(208) 639-0366,(208) 467-1508
2246,2520,Rick,67,527 Catalpa Rd Arcadia CA 91007-6018,(626) 626-6211,(626) 447-5212,NaN,NaN,NaN
2257,2531,Rick,61,227 S Dewey Ave Middleton ID 83644-5585,(208) 585-6333,NaN,NaN,NaN,NaN

In [26]:
print(duplicate)

      Unnamed: 0                  Name  Age  \
158          186  Bobby Everitt Mickey   81
169          197      Carolyn M Mickey   60
173          201      Carolyn K Mickey   60
178          206     Barbara Jo Mickey   77
179          207            A H Mickey   89
182          210         Cessna Mickey   68
198          227        Adele L Mickey   81
227          270            C L Mickey   76
228          275            C L Mickey   76
229          278            C L Mickey   76
235          287                Mickey   79
237          289       E Dpm Mickey Jr   70
246          298        Clayton Mickey   69
252          304        Carla S Mickey   73
256          308           Fran Mickey   90
265          318            A G Mickey   85
271          328                Mickey   79
272          329        Janet S Mickey   61
284          341       Marshall Mickey   80
287          344       Calvin W Mickey   60
294          351   Antoinette M Mickey   81
301          358            M C Mickey   61
306          363        Brian V Mickey   66
309          367          Holly Mickey   72
315          375                Mickey   74
324          384        Debra N Mickey   65
327          390     Donald Lee Mickey   94
329          392        Ellis W Mickey   84
332          401        Brian V Mickey   66
333          403          Arden Mickey   84
...          ...                   ...  ...
1465        1688                  Bill   71
1473        1697                  Bill   74
1686        1920           A Ruth Jeff   61
1715        1949          Cameron Jeff   62
1724        1959         Andersen Jeff   63
1731        1966           Harris Jeff   62
1753        1988              Bob Jeff   71
1771        2006          Bragg C Jeff   60
1784        2019          Anthony Jeff   61
1794        2029            Athey Jeff   62
1981        2228          Bruce J Rick   64
2012        2268                A Rick   63
2015        2271                  Rick   96
2050        2309                  Rick   70
2063        2322                  Rick   63
2083        2342                F Rick   61
2084        2343              A H Rick   69
2121        2381                  Rick   73
2124        2384      Jesus Luis Mateo   65
2126        2386                  Rick   65
2133        2393                A Rick   67
2157        2423                A Rick   61
2160        2426                A Rick   61
2166        2436         Albert H Rick   64
2169        2439      Bruce Arden Rick   76
2188        2460                A Rick   60
2229        2502           Andrew Rick   77
2230        2503          A Jr Rick Jr   64
2246        2520                  Rick   67
2257        2531                  Rick   61

                                                Address          Phone1  \
158   9551 Brookline Ave Desert Hot Springs  CA 9224...  (760) 329-2629
169           569 Olli Trl Maggie Valley  NC 28751-7208  (864) 756-3187
173           569 Olli Trl Maggie Valley  NC 28751-7208  (828) 926-4156
178   9551 Brookline Ave Desert Hot Springs  CA 9224...  (760) 329-6171
179           24215 Taree Dr NE Kingston  WA 98346-9204  (360) 881-0744
182          6507 W Mirabella St Wichita  KS 67205-1002  (316) 641-3888
198          3153 Malvasia Ct Pleasanton  CA 94566-6949  (925) 462-3591
227         1508 El Ralfo Dr Bakersfield  CA 93304-3927  (661) 831-6215
228         1508 El Ralfo Dr Bakersfield  CA 93304-3927  (661) 831-6215
229         1508 El Ralfo Dr Bakersfield  CA 93304-3927  (661) 831-6215
235              3967 Delos Dr Las Vegas  NV 89103-2534  (702) 252-0497
237           9258 Troon Lakes Dr Naples  FL 34109-4314  (239) 598-5363
246              7460 Mellotts Rd Fenton  IL 61251-9793  (309) 887-9271
252                     PO Box 153 Boise  ID 83701-0153  (208) 938-2804
256          401 S 5th St E #33 Chewelah  WA 99109-9300  (509) 935-4861
265        11322 S Avenue 12 E #239 Yuma  AZ 85367-6652  (928) 342-1093
271              3967 Delos Dr Las Vegas  NV 89103-2534  (702) 252-0497
272                20 Robert Ln Ringgold  GA 30736-7200  (423) 637-2890
284          310 St Cloud Rd Los Angeles  CA 90077-3423  (310) 553-0177
287   1712 Ferguson Valley Rd Mc Veytown  PA 17051-9519  (814) 329-5520
294   1841 Spring Mountain Rd Saint Helena  CA 94574...  (707) 968-5375
301             1556 Andrew Ave Anderson  CA 96007-2964  (775) 293-2449
306           3301 Meadowlands Dr Sparks  NV 89431-1448  (775) 331-7409
309        1880 E 10th St Silver Springs  NV 89429-8659  (574) 527-5017
315                1518 Delany St Pomona  CA 91767-4229  (909) 964-7585
324       14049 State Highway 33 Gustine  CA 95322-9793  (503) 227-3357
327        17033 Woodcrest Dr NE Bothell  WA 98011-5426  (425) 968-8910
329               422 4th St Summerville  OR 97876-8169  (541) 534-5418
332           3301 Meadowlands Dr Sparks  NV 89431-1448  (775) 331-7409
333   3215 E Cheyenne Ave North Las Vegas  NV 89030-...  (702) 262-3990
...                                                 ...             ...
1465             213 Ruby St SE Tumwater  WA 98501-4544  (360) 534-0441
1473          5432 99th Ave SE Snohomish  WA 98290-5707  (314) 226-0745
1686     10171 Frontier Pl NW Silverdale  WA 98383-9408  (360) 613-5304
1715             1350 Stella Rd Longview  WA 98632-9727  (360) 414-7017
1724          1163 Wendell St Twin Falls  ID 83301-4275  (208) 420-5530
1731              825 Country Clb Tooele  UT 84074-9627  (435) 841-7332
1753      4403 Blackstone Way Bellingham  WA 98226-7780  (360) 383-0213
1771        2400 Calkins Ave Idaho Falls  ID 83402-4535  (208) 227-6435
1784           3028 Eggleston Rd Crowley  TX 76036-5604  (817) 297-7121
1794             2033 1st Ave #8 Seattle  WA 98121-2132  (206) 448-7832
1981                 1016 W St NW Auburn  WA 98001-3832  (253) 850-1571
2012           630 NE Newkirk Rd Belfair  WA 98528-9689  (253) 344-1489
2015            9218 Williams Rd Chardon  OH 44024-9296  (440) 286-7213
2050      1123 Treemont Way SE Fall City  WA 98024-7426  (949) 612-8396
2063             3157 Maple St San Diego  CA 92104-5026  (619) 890-7425
2083          2720 Barreville Rd McHenry  IL 60050-8113  (406) 461-1446
2084          15834 Kamb Rd Mount Vernon  WA 98273-8142  (360) 424-5934
2121       8842 Midvale Ave N #A Seattle  WA 98103-4034  (949) 654-9614
2124        933 W Nebraska Ave Caruthers  CA 93609-9705  (559) 864-4340
2126       325 Washington Ave S #10 Kent  WA 98032-5767  (714) 446-8890
2133      5564 SW Erickson Ave Beaverton  OR 97005-3882  (503) 919-4070
2157         1018 E 3rd St #D Long Beach  CA 90802-3453             NaN
2160         1018 E 3rd St #D Long Beach  CA 90802-3453             NaN
2166        1227 S 4th Ave #13 Pocatello  ID 83201-6716  (208) 232-0003
2169  203 Hitchcock Way #201 Santa Barbara  CA 93105...  (805) 845-0922
2188           13117 287th Ave SE Monroe  WA 98272-7508  (615) 943-7770
2229             1220 6th Ave SW Olympia  WA 98502-5420  (360) 753-4941
2230          10254 W Shelborne Dr Boise  ID 83709-1230  (208) 514-0136
2246              527 Catalpa Rd Arcadia  CA 91007-6018  (626) 626-6211
2257           227 S Dewey Ave Middleton  ID 83644-5585  (208) 585-6333

              Phone2          Phone3          Phone4          Phone5
158   (760) 329-6171  (541) 726-5035             NaN             NaN
169   (828) 926-4156  (864) 283-0965  (706) 496-8484  (714) 668-0281
173   (864) 283-0965  (714) 668-0281             NaN             NaN
178   (541) 747-3485  (760) 329-2629             NaN             NaN
179   (360) 297-8235  (334) 297-8235             NaN             NaN
182   (316) 641-7774  (316) 721-1410  (316) 409-6374             NaN
198   (510) 388-5349  (925) 462-4293  (415) 462-4293  (510) 462-4293
227              NaN             NaN             NaN             NaN
228              NaN             NaN             NaN             NaN
229              NaN             NaN             NaN             NaN
235   (702) 376-7125  (702) 254-6591             NaN             NaN
237   (239) 250-1133  (239) 250-1333  (239) 566-8800             NaN
246   (815) 772-7211  (417) 628-3383  (208) 289-5033  (509) 758-7963
252              NaN             NaN             NaN             NaN
256   (509) 884-0851             NaN             NaN             NaN
265   (208) 264-5295  (208) 683-3527             NaN             NaN
271   (702) 376-7125  (702) 254-6591             NaN             NaN
272   (423) 595-9247  (706) 595-9247             NaN             NaN
284   (310) 476-3347  (310) 476-0000  (310) 476-0947  (310) 201-7700
287   (814) 542-3434  (814) 542-8068             NaN             NaN
294   (941) 330-4344  (941) 928-1626  (216) 320-9328             NaN
301   (216) 990-8212  (530) 510-5518             NaN             NaN
306   (702) 324-7663  (775) 826-3044  (206) 542-5670  (775) 324-7663
309   (219) 544-1056  (574) 267-6608             NaN             NaN
315   (909) 629-8592             NaN             NaN             NaN
324   (916) 604-2534  (916) 676-3734  (207) 827-6203  (702) 229-4191
327   (425) 896-0312  (702) 363-2380             NaN             NaN
329              NaN             NaN             NaN             NaN
332   (775) 826-3044             NaN             NaN             NaN
333   (702) 682-7755             NaN             NaN             NaN
...              ...             ...             ...             ...
1465             NaN             NaN             NaN             NaN
1473  (214) 435-6498  (360) 853-7672             NaN             NaN
1686  (360) 697-5884  (360) 697-7120             NaN             NaN
1715  (360) 423-5401  (925) 930-7671             NaN             NaN
1724  (208) 736-7426  (208) 669-4064             NaN             NaN
1731  (435) 882-4540  (801) 882-4540  (435) 882-2492  (909) 875-4067
1753  (360) 366-2291  (360) 384-4957  (206) 384-4957             NaN
1771  (208) 521-1851  (208) 523-3843  (208) 709-0841  (208) 948-4542
1784  (817) 426-2061  (310) 422-8911  (702) 468-0547  (775) 468-0547
1794  (816) 531-0590  (208) 762-3779  (816) 359-6499             NaN
1981             NaN             NaN             NaN             NaN
2012  (253) 445-0387  (253) 874-0184  (253) 770-1094  (907) 966-2777
2015  (281) 914-7731  (440) 413-0456             NaN             NaN
2050  (949) 474-0756  (714) 330-5950             NaN             NaN
2063  (619) 969-1634  (619) 754-3582             NaN             NaN
2083  (406) 458-8923  (386) 437-2100             NaN             NaN
2084  (360) 387-6613  (360) 422-6406             NaN             NaN
2121  (714) 654-9614  (949) 362-5278  (562) 595-1261  (949) 595-1261
2124  (559) 916-3395  (559) 976-3395  (559) 864-8182  (559) 864-8204
2126  (714) 990-5596             NaN             NaN             NaN
2133  (347) 223-9579  (503) 329-3139             NaN             NaN
2157             NaN             NaN             NaN             NaN
2160             NaN             NaN             NaN             NaN
2166  (202) 232-0003  (208) 573-4698             NaN             NaN
2169  (805) 620-0740  (520) 408-1700             NaN             NaN
2188  (518) 541-3641  (707) 438-0292  (405) 359-1883  (410) 643-5798
2229  (360) 533-0242  (360) 943-6403             NaN             NaN
2230  (208) 272-1289  (805) 485-0000  (208) 639-0366  (208) 467-1508
2246  (626) 447-5212             NaN             NaN             NaN
2257             NaN             NaN             NaN             NaN

[137 rows x 9 columns]

In [28]:
df.to_csv("~/Desktop/tmp.csv")

In [29]:
df.shape

(2307, 9)

In [37]:
df = df.drop_duplicates(subset={"Names"})

KeyError: Index(['Names'], dtype='object')

In [33]:
df.shape

(2307, 9)